language: go

go:
  - 1.13.x

# before_install:
#   - go get github.com/mattn/goveralls

env: GO111MODULE=on

install:
  # - go get github.com/rakyll/statik
  - true

script:
  - make test
  - make godict
  # - goveralls -service=travis-ci

before_deploy:
  - go get github.com/mitchellh/gox
  - gox -os="linux darwin windows" -arch="386 amd64" -output="{{.Dir}}-{{.OS}}-{{.Arch}}/{{.Dir}}"
  - |
      for os in linux darwin windows; do
        for arch in 386 amd64; do
          cp README.md LICENSE godict-$os-$arch
          zip -r godict-$os-$arch.zip godict-$os-$arch
        done
      done

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: godict-*-*.zip
  skip_cleanup: true
  on:
    tags: true
    go: "1.13.x"
